### ISSUE TITLE
Create Transaction ORM model

### ISSUE THREAD

**Issue by th4ruka** [cey-labs/fin-tracker-backend#4]
## Description:
Create Transaction ORM model to handle transactions within an account. 

## TODO:
* [x] Create ORM model for Transactions inside `/app/models/models.py`
* [x] Create Pydantic schemas for Transaction inside `/app/models/schemas.py`
* [x] Create CRUD Operations for Transactions in the `/app/services/db_services.py`
* [x] Write path operations for Transactions API endpoints inside `/main.py`

* Refer the existing code for `User` and `Account` ORM models.
