### ISSUE TITLE
Write unit-tests for TransactionsService, Transaction model and Transaction schemas

### ISSUE THREAD

**Issue by th4ruka** [cey-labs/fin-tracker-backend#8]
## Description:
Create unit-tests for TransactionsServices, Transaction model and Transaction schemas, inside `/tests/`.
Follow the same directory structure as in `/app/' to create tests inside `/tests/`.

## TODO:
* [ ] Write unit-tests for Transaction model.
* [ ] Write unit-tests for Transaction schema.
* [ ] Write unit-tests for TransactionsServices.
